spring.application.name=gymflow
spring.datasource.url=jdbc:postgresql://localhost:5432/gymflow
spring.datasource.username=gymflow_user
spring.datasource.password=gymflow123

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true